#!/bin/bash
# The adapted stage: every recipe the frozen stages selected, trained with
# adapters at the depth its frozen counterpart was best at.
#
# Runs are written to one place regardless of who launches them, so that the
# probes of a programme stay together and a result can be read without knowing
# whose allocation paid for it. Point OUTPUT_ROOT elsewhere to keep a set apart.
#
# The step cap is a backstop rather than the target: the rule that ends a run
# reads coverage of the tokens before the frontier and typically calls a stop
# between step 200 and step 800. The checkpoint each run is judged on is the one
# named in its selection_outcomes.json, not the weights left in final/.
#
# The whole validation split is monitored, which is not an economy that can be
# made here. The threshold sits above the highest-scoring one percent of healthy
# answers, so a monitor of four hundred would rest it on three of them, and an
# adapted run cannot be replayed afterwards to do better.
set -euo pipefail

OUTPUT_ROOT=${OUTPUT_ROOT:-/iopsstor/scratch/cscs/mdenegri/degeneration-probe/outputs}
cd "$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"

echo "Writing runs to $OUTPUT_ROOT"
if [[ ! -w $OUTPUT_ROOT ]]; then
    echo "Cannot write to $OUTPUT_ROOT." >&2
    echo "Its owner grants the group access with:" >&2
    echo "    setfacl -m g::rwx $OUTPUT_ROOT" >&2
    echo "chmod g+w will not do it: with an ACL present that widens the mask" >&2
    echo "and leaves the group entry read-only." >&2
    exit 1
fi

# S1: rollout_balanced W=128, depth 15
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=rollout_balanced training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=42 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S1"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=rollout_balanced training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=43 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S1"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=rollout_balanced training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=44 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S1"]'

# S1: frontier_window W=256, depth 15
sbatch --time=09:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=256 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=42 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S1"]'
sbatch --time=09:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=256 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=43 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S1"]'
sbatch --time=09:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=256 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=44 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S1"]'

# S1: frontier_window_hard_negative W=256, depth 15 -- NOT LAUNCHED.
# Placing a hard negative window needs to know where a healthy answer looks
# repetitive. The frozen path supplies that signal and the adapted path does
# not, so this recipe fails at startup rather than training. Restore these
# three runs once the signal reaches the adapted dataset.

# S1: random_window W=64, depth 12
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=random_window training.selection.window_size=64 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=12 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=42 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S1"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=random_window training.selection.window_size=64 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=12 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=43 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S1"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=random_window training.selection.window_size=64 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=12 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=44 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S1"]'

# S1: all_tokens W=128, depth 12
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=all_tokens training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=12 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=42 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S1"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=all_tokens training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=12 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=43 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S1"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=all_tokens training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=12 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=44 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S1"]'

# S2a: frontier_window W=512, depth 15
sbatch --time=07:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=256 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=512 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=42 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2a"]'
sbatch --time=07:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=256 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=512 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=43 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2a"]'
sbatch --time=07:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=256 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=512 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=44 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2a"]'

# S2a: all_tokens W=128, depth 15
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=1024 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=all_tokens training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=42 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2a"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=1024 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=all_tokens training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=43 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2a"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=1024 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=all_tokens training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=44 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2a"]'

# S2a: frontier_window W=512, depth 15
sbatch --time=07:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=512 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=trailing training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=512 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=42 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2a"]'
sbatch --time=07:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=512 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=trailing training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=512 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=43 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2a"]'
sbatch --time=07:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=512 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=trailing training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=512 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=44 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2a"]'

# S2a: all_tokens W=128, depth 15
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=256 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=all_tokens training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=42 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2a"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=256 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=all_tokens training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=43 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2a"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=256 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=all_tokens training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=44 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2a"]'

# S2b: frontier_window W=512, depth 15
sbatch --time=07:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_soft training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=false training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=512 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=42 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2b"]'
sbatch --time=07:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_soft training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=false training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=512 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=43 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2b"]'
sbatch --time=07:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_soft training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=false training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=512 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=44 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2b"]'

# S2b: frontier_window W=512, depth 15
sbatch --time=07:00:00 cluster/train.sbatch training.label.decay=linear training.label.decay_length=256 training.label.family=frontier_soft training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=false training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=512 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=42 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2b"]'
sbatch --time=07:00:00 cluster/train.sbatch training.label.decay=linear training.label.decay_length=256 training.label.family=frontier_soft training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=false training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=512 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=43 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2b"]'
sbatch --time=07:00:00 cluster/train.sbatch training.label.decay=linear training.label.decay_length=256 training.label.family=frontier_soft training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=false training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=512 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=15 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=44 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2b"]'

# S2c: frontier_window W=128, depth 11
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=token_signal training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=mse training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=11 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=42 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2c"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=token_signal training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=mse training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=11 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=43 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2c"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=token_signal training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=mse training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=11 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=44 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2c"]'

# S2d: frontier_window W=128, depth 4
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=4 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=42 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2d"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=4 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=43 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2d"]'
sbatch --time=12:00:00 cluster/train.sbatch training.label.decay=exponential training.label.decay_length=256 training.label.family=frontier_hard training.label.horizon=0 training.label.signal=repetition_score training.loss.bce.use_pos_weight=true training.loss.name=bce training.selection.anchor=centered training.selection.positive_fraction=0.25 training.selection.strategy=frontier_window training.selection.window_size=128 training.features.regime=adapted training.lora.enabled=true training.lora.layers=all training.lora.rank=16 training.optimizer.lora_learning_rate=1e-5 training.optimizer.probe_learning_rate=1e-4 training.probe.layers=null training.probe.layer=4 training.budget.tokens_per_step=4096 training.runtime.per_device_train_batch_size=1 training.runtime.seed=44 training.runtime.max_steps=2000 training.validation.strategy=steps training.validation.steps=50 training.validation.max_rollouts=null 'training.validation.final_splits=[]' training.checkpoint.strategy=steps training.checkpoint.steps=50 training.checkpoint.save_total_limit=null training.checkpoint.root_dir="$OUTPUT_ROOT" training.stopping.enabled=true training.stopping.floor=0.3 training.stopping.band=256 training.stopping.tolerance=0.002 training.stopping.patience=4 'training.wandb.tags=["exp:S3","carried:S2d"]'

echo "Submitted 36 runs to $OUTPUT_ROOT"
